import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { PageHeader } from '@/components/layout/PageHeader'
import { Stack, Title, Text } from '@mantine/core'
import { greetings } from '@/helpers/greetings'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const greetingMessage = greetings();
  return (
    <>
      <Head>
        <title>UofG Prepare</title>
      </Head>
			<PageHeader
				heading="Homepage"
				subheading={`${greetingMessage}`}
			/>
			<Stack>
				<Title order={1} size="h1">
					Welcome to Prepare
        </Title>
                <Text>
                Welcome to Prepare, a system to help you get setup and ready for starting you university journey. 
                This system is specialised to the schools of chemistry and physics. Here you will find advice and tools to help you get set up for starting uni, as ell as useful areas for throughout your time in your first year, such as study tools and advice. 
                We hope you find this system useful in helping prepare you to be a future world changer.
                </Text>
           </Stack>
		</>
    // <>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <main className={`${styles.main} ${inter.className}`}>
    //     <div className={styles.description}>
    //       <p>
    //         Get started by editing&nbsp;
    //         <code className={styles.code}>src/pages/index.tsx</code>
    //       </p>
    //       <div>
    //         <a
    //           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //           target="_blank"
    //           rel="noopener noreferrer"
    //         >
    //           By{' '}
    //           <Image
    //             src="/vercel.svg"
    //             alt="Vercel Logo"
    //             className={styles.vercelLogo}
    //             width={100}
    //             height={24}
    //             priority
    //           />
    //         </a>
    //       </div>
    //     </div>

    //     <div className={styles.center}>
    //       <Image
    //         className={styles.logo}
    //         src="/next.svg"
    //         alt="Next.js Logo"
    //         width={180}
    //         height={37}
    //         priority
    //       />
    //     </div>

    //     <div className={styles.grid}>
    //       <a
    //         href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2>
    //           Docs <span>-&gt;</span>
    //         </h2>
    //         <p>
    //           Find in-depth information about Next.js features and&nbsp;API.
    //         </p>
    //       </a>

    //       <a
    //         href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2>
    //           Learn <span>-&gt;</span>
    //         </h2>
    //         <p>
    //           Learn about Next.js in an interactive course with&nbsp;quizzes!
    //         </p>
    //       </a>

    //       <a
    //         href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2>
    //           Templates <span>-&gt;</span>
    //         </h2>
    //         <p>
    //           Discover and deploy boilerplate example Next.js&nbsp;projects.
    //         </p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2>
    //           Deploy <span>-&gt;</span>
    //         </h2>
    //         <p>
    //           Instantly deploy your Next.js site to a shareable URL
    //           with&nbsp;Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>
    // </>
  )
}
